config/routes.rb
Rails.application.routes.draw do
   
  
  get 'downgrade' =>'users#downgrade'


  resources :charges, only: [:new, :create]

  resources :wikis do
    resources :collaborators, only: [:create, :destroy]
  end

  devise_for :users
  
  get 'welcome/index'

  get 'about' => 'welcome#about'

  root to:'welcome#index'
  
end

app/models/amount.rb
class Amount < ActiveRecord::Base
	
 #default membership amount	 
 def self.default
    @amount = 15_00
  end
end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base

  belongs_to :user
  belongs_to :wiki
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_many :wikis
  #has_many :collaborators

  
  #after_initialize :set_role

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable   

  def admin?
  	role == 'admin'
  end  

  def moderator?
    role == 'premium'
  end

  def standard?
    self.role == 'standard'
  end

  
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base

  belongs_to :user
  has_many :collaborators
  has_many :users, through: :collaborators

  #scope :visisble_to, -> (user) { user ? all : where(public: true) }
 
  scope :visible_to, -> (user) { user && ((user.role == 'premium') || (user.role == 'admin')) ? all : where((private == false) || (private == nil))  }

  def collaborator_for(user)
    collaborators.where(user: user).first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from Pundit::NotAuthorizedError do |exception|
  	redirect_to root_url, alert: excetion.message
  end

  protected

    def after_sign_in_path_for(resource)
      wikis_path
    end


   def configure_permitted_parameters
     devise_parameter_sanitizer.for(:sign_up) << :name
   end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  
 def create
   
   # Creates a Stripe Customer object, for associating with the charge
   customer = Stripe::Customer.create(
     email: current_user.email,
     card: params[:stripeToken]
   )
 
   # Where the real magic happens
   charge = Stripe::Charge.create(
     customer: customer.id, # Note -- this is NOT the user_id in your app
     amount: Amount.default,
     description: "Premium Membership - #{current_user.email}",
     currency: 'usd'
   )

   #if current_user.update(premium :true)
    current_user.update_attribute(:role, 'premium')

   flash[:notice] = "Thanks for all the money, #{current_user.email}! Membership upgraded to Premium."
   redirect_to edit_user_registration_path(current_user) # or wherever
   
   # Stripe will send back CardErrors, with friendly messages when something goes wrong.
   # This `rescue block` catches and displays those errors.
   rescue Stripe::CardError => e
     flash[:alert] = e.message
     redirect_to new_charge_path
  end
  
  def new
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "Premium Membership - #{current_user.name}",
      amount: Amount.default
    }	
  end
end

#Set default Premium Membership amount
#class Amount

#  def self.default
#    @amount = 15_00
#  end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController

  before_action :set_wiki

  def new
  end

  def create
  	@collaborator = Collaborator.new(wiki_id: @wiki.id, user_id: params[:user_id])
  	if @collaborator.save
  	  flash[:notice] = "Wiki was saved."
      redirect_to edit_wiki_path(@wiki)
    else
      flash[:error] = "Error when saving. Plese try again."
      render :new
    end
  end

  def destroy
    @collaborator = Collaborator.find(params[:id])
    if @collaborator.destroy
      flash[:notice] = "Wiki was updated."
      redirect_to @wiki
    else
      flash[:error] = "Error when saving. Please try again."
      #redirect, notice: @collaborator.errors.full_messages
      render :new
    end
  end

  private

  def set_wiki
    @wiki = Wiki.find(params[:wiki_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

#allow user to change from Premium to Standard membership	
  def downgrade
    current_user.update_attribute(:role, 'standard')
      
    current_user.wikis.each do |wiki|
      wiki.update_attribue(:private, false)
    #wiki.private_wikis(current_user).update_attribute(private :false)
  end
    else
      #flash[:error] = "Invalid user information"
      redirect_to root_path
    end
  end 

  private

    def user_params
      params.require(:user).permit(:name, :role)
    end 

    def wiki_params(wiki)
      params.require(:wiki).permit(:private)
    end  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController

  
  def index
  	@wikis = policy_scope(Wiki)
    #@wikis = Wiki.visible_to(current_user).where("wikis.created_at > ?", 7.days.ago).paginate(page: params[:page], per_page: 10)
    #authorize @wikis
  end

  def show
    @wiki = Wiki.find(params[:id])
    #@wikis = @wikis.includes(:user).includes(:comments).paginate(page: params[:page], per_page: 10)
    authorize @wiki
    
  end

  def new
  	@wiki = Wiki.new
    #@users = User.all
    #authorize @wiki
  end

  def create
    @wiki = Wiki.new(wiki_params)
    #@wiki = Wiki.new(wiki_params)
    @wiki.user = current_user
    #@user = @wiki.user
    authorize @wiki
    if @wiki.save
    	flash[:notice] = "Wiki was saved."
    	redirect_to @wiki
    else
    	flash[:error] = "Error when saving. Plese try again."
    	render :new
    end
  end

  def edit
  	@wiki = Wiki.find(params[:id])
    @users = User.all
    authorize @wiki
  end

  def update
  	@wiki = Wiki.find(params[:id])
    authorize @wiki
  	if @wiki.update_attributes(wiki_params)
  	  flash[:notice] = "Wiki was updated."
  	  redirect_to @wiki
  	else
      flash[:notice] = "Error updating the wiki. Please try again."
      render :edit
    end
  end

  def destroy
  	@wiki = Wiki.find(params[:id])
    #authorize @wiki
  	if @wiki.destroy
  	  flash[:notice] = "Wiki was deleted."
  	  redirect_to wiki_path
  	else
  	  flash[:error] = "Error when deleting wiki. Try again."
  	  render :show
    end
  end

  def downgrade
    current_user.downgrade
    flash[:notice] = "You're account is now at Standard"
    redirect_to index_path
  end


  private 

  def wiki_params
    params.require(:wiki).permit(:title, :body, :publc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def markdown_to_html(markdown)
    renderer = Redcarpet::Render::HTML.new
    extensions = {fenced_code_blocks: true}
    redcarpet = Redcarpet::Markdown.new(renderer, extensions)
    (redcarpet.render markdown).html_safe
  end
  
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/edit.html.erb
<h1>Charges#edit</h1>
<p>Find me in app/views/charges/edit.html.erb</p>

app/views/charges/index.html.erb
<h1>Charges#index</h1>
<p>Find me in app/views/charges/index.html.erb</p>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>

  <h4>Click to purchase Premium Membership.</h4>
  <script class='stripe-button' 
  src="https://checkout.stripe.com/checkout.js" 
  data-key="<%= @stripe_btn_data[:key] %>" 
  data-amount=<%= @stripe_btn_data[:amount] %> 
  data-description="<%= @stripe_btn_data[:description] %>" >
  </script>
 <% end %>

 

app/views/charges/show.html.erb
<h1>Charges#show</h1>
<p>Find me in app/views/charges/show.html.erb</p>

app/views/collaborators/create.html.erb
<h1>Collaborators#create</h1>
<p>Find me in app/views/collaborators/create.html.erb</p>

app/views/collaborators/new.html.erb
<h1>Collaborators#new</h1>
<p>Find me in app/views/collaborators/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <meta name="viewport" content="width=device-width, inital-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %> 

  <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
  
  <script type="text/javascript">
  // This identifies your website in the createToken call below
  Stripe.setPublishableKey('pk_test_LpviKpiWPQ6i3dwBhR1JlAig');
  // ...
  </script>


</head>
<body>
  <div class="container">
	<ul class="nav nav-tabs">
      <li><%= link_to "Home", root_path %></li>
	  <li><%= link_to "About", about_path %></li>
	</ul>
	<!--Flash Notices -->
	<% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
       </div>
    <% elsif flash[:error] %>
       <div class="alert alert-danger">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:error] %>
        </div>
    <% elsif flash[:alert] %>
       <div class="alert alert-warning">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:alert] %>
        </div>
     <% end %>		

	<div class="pull-right user-info">
	  <% if current_user %>
		Welcome <%= current_user.email %>! <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
	  <% else %>
		<%= link_to "Sign In", new_user_session_path %> or
		<%= link_to "Sign Up", new_user_registration_path %>
	  <% end %>
	</div>

		
	  <%= yield %>
    </div>

  </body>
</html>

app/views/users/downgrade.html.erb
<p>Thank you, your account has been downgraded to: <%= current_user.role %>.</p>

app/views/welcome/about.html.erb
<h1>Welcome home.</h1>
<p>This page is about you. Your membership is.</p>

app/views/welcome/index.html.erb
<h2>This is you account page.</h2>
<p>We offer Premium Membership at $15 a year.</p>

 

app/views/wikis/_form.html.erb
<div class="row">
  <div class="col-md-4">
    <%= form_for wiki do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title." %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body." %>
      </div>
  
      <!--Test for Private Wiki access -->
      
    
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/wikis/edit.html.erb
<h1>Edit Wiki Collaborators</h1>
  <%= render partial: 'form', locals: { wiki: @wiki } %>

  <% if current_user.role == 'premium' %>
  
  <% @users.each do |user| %>
    <%= user.name %>  
      <div class="form-group">  
      <% if @wiki.users.include? user %>
        <%= link_to "Delete Collaborator", wiki_collaborator_path(@wiki, @wiki.collaborator_for(user)), method: :delete, class: 'btn btn-danger' %>
        <% else %>
        <%= link_to "Add Collaborator", wiki_collaborators_path(@wiki, user_id: user.id), method: :post, class: 'btn btn-success' %>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/wikis/index.html.erb
<h1>All Wikis</h1>

<% if policy(Wiki.new).create? %> 
  <%= link_to "Add a new Wiki.", new_wiki_path, class: 'btn btn-success' %>
<% end %>
  <% @wikis.each do |wiki| %>
  	<div class="media">
      <div class="media-body">
        <h4 class="media-heading">
          <%= link_to wiki.title, wiki %>
        </h4>
      </div>
    </div>
 <% end %>
    

app/views/wikis/new.html.erb
<h1>New Wiki</h1>
 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for wikis</p>
     <ul>
       <li>Do not duplicate Wikis already created.</li>    
     </ul>
   </div>
   <div class="col-md-8">
     <%= form_for @wiki do |f| %>
       <div class="form-group">
         <%= f.label :title %>
         <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
       </div>
       <div class="form-group">
         <%= f.label :body %>
         <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
       </div>
       <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
 </div>

app/views/wikis/show.html.erb
<h1><%= markdown_to_html @wiki.title %></h1>


    <% if policy(@wiki).edit? %>
      <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
    <% end %>


  <% if policy(@wiki).destroy? %>      
  <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this wiki?' } %> 
  <% end %>